# Generated by Django 6.0.6 on 2026-07-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=5)),
                ('units_donated', models.PositiveIntegerField(default=1)),
                ('donation_date', models.DateField()),
                ('certificate_id', models.CharField(blank=True, help_text='Unique certificate ID for verification.', max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_records', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Record',
                'verbose_name_plural': 'Donation Records',
                'ordering': ['-donation_date'],
            },
        ),
    ]
