# Generated by Django 6.0.6 on 2026-07-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('emergency', 'Emergency Request'), ('request_accepted', 'Donation Accepted'), ('request_rejected', 'Donation Rejected'), ('donation_completed', 'Donation Completed'), ('eligibility_update', 'Eligibility Updated'), ('new_request', 'New Blood Request'), ('admin_announcement', 'Admin Announcement'), ('profile_verified', 'Profile Verified'), ('rating_received', 'Rating Received'), ('general', 'General')], default='general', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='Link to navigate to when notification is clicked.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
